-   id: odoo-sort-manifest-depends
    name: Sorting depends of odoo addons manifests
    description: Sorting alphabetically depends of odoo addons manifests
    entry: odoo-sort-manifest-deps
    language: python
    pass_filenames: False
    files: .*/__manifest__.py$
